# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# creates new ec2 key pair. if not present, returns generated
# private key

- name: Set credentials variable to desired role
  set_fact:
    role_credentials: "{{item.NucleatorCageProvisioner}}"
  with_items:
    - "{{aws_environment_with_rolenames}}"
  no_log: True

- name: log credentials variable
  debug: var=role_credentials
  when: debug_credentials

- name: create ec2 keypair
  ec2_key:
    name: "{{ keypair_name }}"
    region: "{{ aws_region }}"
  environment: role_credentials
  register: create_key

- name: set key_material from resulting key
  set_fact:
    key_material: "{{ create_key.key.private_key }}"
  when: create_key.changed

- name: store key in nucleator config directory when new key was created
  template:
    src=key.pem
    dest={{ nucleator_configuration_dir}}/{{ keypair_name }}.pem
    mode=0400
  when: create_key.changed

- include: cage_provision.yml
