# Copyright 2015 47Lining LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

private_acl:

  inbound_entries:
#    - name: InboundFtpPrivateNetworkAclEntry
#      properties:
#        RuleNumber: 100
#        Protocol: 6
#        RuleAction: allow #tcp
#        CidrBlock: 0.0.0.0/0
#        PortRange:
#          From: 21
#          To: 21
    - name: InboundHttpPrivateNetworkAclEntry
      properties:
        RuleNumber: 101
        Protocol: 6 #tcp
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 80
          To: 80
#    - name: InboundHttpsPrivateNetworkAclEntry
#      properties:
#        RuleNumber: 102
#        Protocol: 6 #tcp
#        RuleAction: allow
#        CidrBlock: 0.0.0.0/0
#        PortRange:
#          From: 443
#          To: 443
    - name: InboundSshPrivateNetworkAclEntry
      properties:
        RuleNumber: 103
        Protocol: 6 #tcp
        RuleAction: allow
        CidrBlock: '{{ network_topology.vpc_cidr }}'
        PortRange:
          From: 22
          To: 22
    - name: InboundEphemeralPrivateNetworkAclEntry
      properties:
        RuleNumber: 104
        Protocol: 6 #tcp
        RuleAction: allow
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 1024
          To: 65535
    - name: InboundDnsPrivateNetworkAclEntry
      properties:
        RuleNumber: 105
        Protocol: 17 #udp
        RuleAction: allow
        CidrBlock: '{{ network_topology.vpc_cidr }}'
        PortRange:
          From: 53
          To: 53
    - name: InboundDnsEphemeralPrivateNetworkAclEntry
      properties:
        RuleNumber: 106
        Protocol: 17 #udp
        RuleAction: allow
        CidrBlock: '{{ network_topology.vpc_cidr }}'
        PortRange:
          From: 1024
          To: 65535

  outbound_entries:
    - name: OutboundPrivateNetworkAclEntry
      properties:
        RuleNumber: 100
        Protocol: -1
        RuleAction: allow #tcp
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 0
          To: 65535
